name: Validate

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: List files
        run: ls

      - name: Install Index Generator
        run: |
          Invoke-WebRequest -Uri https://github.com/ClassIsland/ClassIsland.PluginIndexGenerator/releases/download/1.0.1.1/ClassIsland.PluginIndexGenerator.zip -OutFile ClassIsland.PluginIndexGenerator.zip
          Expand-Archive -Path ClassIsland.PluginIndexGenerator.zip -DestinationPath .
      
      - name: Validate Plugin Index
        run: |
          mkdir out/source/
          ./ClassIsland.PluginIndexGenerator.exe index out/source/index.json -b base.json -v true
          

